cache:
    paths:
        - node_modules/

default: 
    image: node:18-alpine3.15

stages: 
    # - prebuild
    - build
    - deploy

workflow: 
    rules: 
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# prebuild: 
#     stage: prebuild
#     before_script:
#         - npm ci
#     script: 
#         - npm run type-check
#         - npm run lint
#         - npm run test


build-pages: 
    stage: build
    before_script: 
        - npm ci
    variables:
        TEST1: ${CI_PROJECT_PATH#$CI_PROJECT_ROOT_NAMESPACE}/
        TEST2: echo ${CI_PROJECT_PATH#$CI_PROJECT_ROOT_NAMESPACE}/
        TEST3: "hello"
    script: 
        - echo $TEST1
        - echo $TEST2
        - echo $TEST3
        - npm run build
    artifacts:
        paths:
            - dist/
        expire_in: 1 day

pages:
    stage: deploy
    image: busybox:latest
    script: 
        - rm -rf public
        - mkdir public
        - mv dist/* public
    artifacts: 
        paths: 
            - public
    rules: 
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


    