stages: 
    - deploy

workflow: 
    rules: 
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
    stage: deploy
    image: busybox:latest
    script: 
        - mv index.html public/index.html
    artifacts: 
        paths: 
            - public


    