cache:
    paths:
        - node_modules/

default: 
    image: node:18-alpine3.15

stages: 
    - build
    - deploy

workflow: 
    rules: 
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build: 
    stage: build
    before_script: 
        - npm ci
    script: 
        - npm run build
    artifacts:
        paths:
            - dist/
        expire_in: 1 day

pages:
    stage: deploy
    image: busybox:latest
    script: 
        - mv dist public
    artifacts: 
        paths: 
            - public
    rules: 
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


    