name: Deploy Library to npm

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Lint, Type-Check, Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - run: npm ci
      - run: npm run lint
      - run: npm run build-lib
      - run: npm run test
      - name: Upload library as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vue-collection-lib
          path: |
            lib
            .npmrc
            package.json
            README.md
  deploy:
    name: Deploy Library to npm
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
          registry-url: https://registry.npmjs.org/
      # Ensure npm 11.5.1 or later for trusted publishing
      - name: Ensure latest npm version
        run: npm --version
      - run: npm install -g npm@latest --no-man
      - name: Download library artifact
        uses: actions/download-artifact@v4
        with:
          name: vue-collection-lib
      - name: Prepare folder structure
        run: mv ./lib/* .
      - run: npm publish --access=public
